# GCP-specific secrets for Onyx deployment
# These secrets contain sensitive configuration data

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onyx-stack.fullname" . }}-gcp-secrets
  labels:
    {{- include "onyx-stack.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials (base64 encoded)
  {{- if .Values.externalPostgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.externalPostgresql.password | b64enc | quote }}
  {{- end }}

  # Redis credentials (if needed)
  {{- if and .Values.externalRedis.enabled .Values.externalRedis.password }}
  REDIS_PASSWORD: {{ .Values.externalRedis.password | b64enc | quote }}
  {{- end }}

  # Google OAuth credentials
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.googleOAuth.clientId | b64enc | quote }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ .Values.googleOAuth.clientSecret | b64enc | quote }}

  # Application secret key
  SECRET: "bjhXW3ptcmd6YWFKOFllT0YzZ2Q0eU9GYkNVVk96ekFaLzNQV3owTVNzK29mbWt1a3k0QWg2dEhlMUVsNnR6MUJtS2RHTjExbUI4ZzI1UmZqOVVVQT09"

  # Database readonly user (if needed)
  {{- if .Values.externalPostgresql.readonlyUser }}
  DB_READONLY_USER: {{ .Values.externalPostgresql.readonlyUser | b64enc | quote }}
  DB_READONLY_PASSWORD: {{ .Values.externalPostgresql.readonlyPassword | b64enc | quote }}
  {{- end }}

  # Cloud Storage credentials (if using service account)
  {{- if .Values.storage.serviceAccountKey }}
  GCP_SERVICE_ACCOUNT_KEY: {{ .Values.storage.serviceAccountKey | b64enc | quote }}
  {{- end }}

  # Model API keys (if needed)
  {{- if .Values.modelServers.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.modelServers.openaiApiKey | b64enc | quote }}
  {{- end }}

  # Additional environment variables
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}